[2019-02-27 12:07:16,062: WARNING/MainProcess] /Users/songpengliang/Library/Python/2.7/lib/python/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2019-02-27 12:07:16,297: INFO/MainProcess] Connected to redis://localhost:6379/0
[2019-02-27 12:07:16,306: INFO/MainProcess] mingle: searching for neighbors
[2019-02-27 12:07:17,315: INFO/MainProcess] mingle: all alone
[2019-02-27 12:07:17,327: WARNING/MainProcess] /Users/songpengliang/Library/Python/2.7/lib/python/site-packages/djcelery/loaders.py:133: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warn('Using settings.DEBUG leads to a memory leak, never '
[2019-02-27 12:07:17,327: WARNING/MainProcess] celery@songpengliangdeMacBook-Pro.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)

worker: Cold shutdown (MainProcess)
 
 -------------- celery@songpengliangdeMacBook-Pro.local v3.1.26.post2 (Cipater)
---- **** ----- 
--- * ***  * -- Darwin-18.0.0-x86_64-i386-64bit
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         default:0x103218810 (djcelery.loaders.DjangoLoader)
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . xjmallapp.tasks.send


worker: Cold shutdown (MainProcess)
[2019-02-27 12:07:26,119: WARNING/MainProcess] Exception
[2019-02-27 12:07:26,120: WARNING/MainProcess] KeyError
[2019-02-27 12:07:26,120: WARNING/MainProcess] :
[2019-02-27 12:07:26,120: WARNING/MainProcess] KeyError(4402521536,)
[2019-02-27 12:07:26,120: WARNING/MainProcess] in
[2019-02-27 12:07:26,120: WARNING/MainProcess] <module 'threading' from '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'>
[2019-02-27 12:07:26,120: WARNING/MainProcess] ignored
